/*
 * Copyright (c)  2026 Zakir Sheikh
 *
 * Created by sheik on 4 of Jan 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Last Modified by sheik on 4 of Jan 2026
 *
 */

package com.zs.common.db.media


import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Ignore
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a media photo/video album
 *
 * @property id Unique identifier for the album. Auto-generated by the database.
 * @property name Display name of the album.
 * @property description Optional user-provided description for the album.
 * @property dateAdded Timestamp when the album was created.
 * @property dateModified Timestamp of the last modification to the album.
 * @property coverID Identifier of the media item used as the album cover.
 *                        If the file is available locally, this is the stored ID;
 *                        otherwise, it refers to the remote source ID.
 *                        Typically calculated as the ID of the most recently added item.
 */
@Entity(tableName = "tbl_albums", indices = [Index(value = ["name"], unique = true)])
class Album internal constructor(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val description: String? = null,
    @ColumnInfo(name = "date_added") val dateAdded: Long = System.currentTimeMillis(),
    @ColumnInfo(name = "date_modified") val dateModified: Long = dateAdded
) {

    @Ignore
    val coverID: String = ""

    /**
     * Represents a Memory within an album.
     *
     * A memory links an album to a media item (photo or video) and stores
     * album-specific metadata such as ordering and the time the media
     * was added to the album.
     *
     * This entity acts as a junction between [Album] and [MediaFile].
     * Deleting either the album or the media item will automatically
     * remove the associated moment.
     *
     * @property albumID Identifier of the album this moment belongs to.
     * @property mediaID Identifier of the media item associated with this moment.
     * @property dateAdded Timestamp when the media item was added to the album.
     * @property order Position of the memory within the album.
     */
    @Entity(
        tableName = "tbl_memories", primaryKeys = ["album_id", "media_id"],
        indices = [Index("album_id"), Index("media_id")],
        foreignKeys = [
            ForeignKey(
                entity = Album::class,
                parentColumns = ["id"],
                childColumns = ["album_id"],
                onDelete = ForeignKey.CASCADE
            ),
            ForeignKey(
                entity = MediaFile::class,
                parentColumns = ["id"],
                childColumns = ["media_id"],
                onDelete = ForeignKey.CASCADE
            )
        ],
    )
    class Memory(
        @ColumnInfo(name = "media_id") val mediaID: Long,
        @ColumnInfo(name = "album_id") val albumID: Long,
        val dateAdded: Long = System.currentTimeMillis(),
        val order: Int
    ) {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (javaClass != other?.javaClass) return false

            other as Memory

            if (mediaID != other.mediaID) return false
            if (albumID != other.albumID) return false
            if (dateAdded != other.dateAdded) return false
            if (order != other.order) return false

            return true
        }

        override fun hashCode(): Int {
            var result = mediaID.hashCode()
            result = 31 * result + albumID.hashCode()
            result = 31 * result + dateAdded.hashCode()
            result = 31 * result + order
            return result
        }

        override fun toString(): String {
            return "Memory(mediaID=$mediaID, albumID=$albumID, dateAdded=$dateAdded, order=$order)"
        }
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Album

        if (id != other.id) return false
        if (dateAdded != other.dateAdded) return false
        if (dateModified != other.dateModified) return false
        if (name != other.name) return false
        if (description != other.description) return false
        if (coverID != other.coverID) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + dateAdded.hashCode()
        result = 31 * result + dateModified.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + (description?.hashCode() ?: 0)
        result = 31 * result + coverID.hashCode()
        return result
    }

    override fun toString(): String {
        return "Album(id=$id, name='$name', description=$description, dateAdded=$dateAdded, dateModified=$dateModified, coverMediaID='$coverID')"
    }
}