/*
 * Copyright (c)  2025 Zakir Sheikh
 *
 * Created by sheik on 23 of Dec 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Last Modified by sheik on 23 of Dec 2025
 */

package com.zs.common.db.albums

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a memory belonging to an album.
 *
 * A memory links an album to a media item (photo or video) and may contain ordering
 *
 * @property id Unique identifier for the album. Auto-generated by the database.
 * @property name Display name of the album. Must be unique.
 * @property description Optional user-provided description for the album.
 * @property dateAdded Timestamp when the album was created.
 * @property dateModified Timestamp of the last modification to the album.
 */
@Entity(tableName = "tbl_albums", indices = [Index(value = ["name"], unique = true)])
class Album internal constructor(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val description: String? = null,
    @ColumnInfo(name = "date_added") val dateAdded: Long = System.currentTimeMillis(),
    @ColumnInfo(name = "date_modified") val dateModified: Long = dateAdded
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Album

        if (id != other.id) return false
        if (dateAdded != other.dateAdded) return false
        if (dateModified != other.dateModified) return false
        if (name != other.name) return false
        if (description != other.description) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + dateAdded.hashCode()
        result = 31 * result + dateModified.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + (description?.hashCode() ?: 0)
        return result
    }

    /**
     * Returns a new [Album] instance with updated metadata.
     *
     * @param name New display name for the album. Defaults to the current name.
     * @param description New optional description for the album.
     */
    fun update(name: String = this.name, description: String? = this.description): Album =
        Album(
            id = id,
            name = name,
            description = description,
            dateAdded = dateAdded,
            dateModified = System.currentTimeMillis()
        )

    override fun toString(): String {
        return "Album(id=$id, name='$name', description=$description, dateAdded=$dateAdded, dateModified=$dateModified)"
    }

    /**
     * Represents a moment within an album.
     *
     * A moment links an album to a media item (photo or video) and stores
     * album-specific metadata such as ordering and the time the media
     * was added to the album.
     *
     * This entity acts as a junction between [Album] and [MediaFile].
     * Deleting either the album or the media item will automatically
     * remove the associated moment.
     *
     * @property albumId Identifier of the album this moment belongs to.
     * @property mediaId Identifier of the media item associated with this moment.
     * @property dateAdded Timestamp when the media item was added to the album.
     * @property thumbnail url of the thumbnail of the movement.
     * @property order Position of the memory within the album.
     */
    @Entity(
        tableName = "tbl_album_moment", primaryKeys = ["album_id", "media_id"],
        indices = [Index("album_id"), Index("media_id")],
        foreignKeys = [ForeignKey(
            entity = Album::class,
            parentColumns = ["id"],
            childColumns = ["album_id"],
            onDelete = ForeignKey.CASCADE
        ), ForeignKey(
            entity = MediaFile::class,
            parentColumns = ["id"],
            childColumns = ["media_id"],
            onDelete = ForeignKey.CASCADE
        )],
    )
    class Memory(
        @ColumnInfo(name = "album_id") val albumId: Long,
        @ColumnInfo(name = "media_id") val mediaId: Long,
        val thumbnail: String,
        val dateAdded: Long = System.currentTimeMillis(),
        val order: Int
    ) {

        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (javaClass != other?.javaClass) return false

            other as Memory

            if (albumId != other.albumId) return false
            if (mediaId != other.mediaId) return false
            if (dateAdded != other.dateAdded) return false
            if (order != other.order) return false
            if (thumbnail != other.thumbnail) return false

            return true
        }

        override fun hashCode(): Int {
            var result = albumId.hashCode()
            result = 31 * result + mediaId.hashCode()
            result = 31 * result + dateAdded.hashCode()
            result = 31 * result + order
            result = 31 * result + thumbnail.hashCode()
            return result
        }


        override fun toString(): String {
            return "Memory(albumId=$albumId, mediaId=$mediaId, thumbnail='$thumbnail', dateAdded=$dateAdded, order=$order)"
        }
    }
}